services:
  db:
    image: postgres:17-alpine
    container_name: big_brother_db
    environment:
      POSTGRES_DB: big_brother
      POSTGRES_USER: big_bro
      POSTGRES_PASSWORD: big_bro
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U big_bro -d big_brother"]
      interval: 10s
      timeout: 5s
      retries: 5

  mailhog:
    image: mailhog/mailhog:latest
    container_name: big_brother_mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  pgdata: