spring:
  config:
    import: optional:file:.env[.properties]

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

  logging:
    level:
      com.expensetracker: DEBUG
      org.springframework.security: DEBUG
      org.hibernate.sql: DEBUG
      org.hibernate.type.descriptor.sql: TRACE

  server:
    port: 8080

app:
  rate-limit:
    capacity: 30
    refill-rate: 10
    refill-period-seconds: 60

